// lib/email-sections/generated-image.js
//
// A single AI-generated PNG, no surrounding copy. Used when the visual is
// the message — product mockups, comparison cards, pricing tables, stats
// blocks that read better as one rich image than as inline HTML.
//
// Generated by the Stage B pipeline at /api/image-generate-v2.
// The composer may propose this section type when editorial-quality
// visuals beat structured HTML. The user generates the image via the
// per-slot Generate button.
//
// Author: Travelgenix
// Date:   18 May 2026 (Stage C)

const { BRAND, FONTS } = require("../email-brand");
const { escHtml, safeUrl, fallback } = require("./_helpers");

function render(props = {}) {
  const imageUrl = safeUrl(props.imageUrl);
  const imageAlt = escHtml(props.imageAlt || "");
  const caption = props.caption ? escHtml(props.caption) : "";
  // Width is capped at 600 to fit the email container; height scales.
  // The pipeline returns 2400x1200 (etc) — the email shows it responsive.
  const declaredWidth = Math.min(parseInt(props.width, 10) || 600, 600);

  // No URL yet: render a "not generated" placeholder. The validator
  // should prevent this making it to send, but fail-safe just in case.
  if (!imageUrl) {
    return `
<tr><td bgcolor="${BRAND.surface}" class="tg-pad-mobile" style="background-color:${BRAND.surface};padding:32px;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" style="border:2px dashed ${BRAND.border || '#E2E8F0'};border-radius:8px;padding:48px 24px;font-family:${FONTS.body};font-size:14px;color:${BRAND.inkSoft};">
Image not yet generated.
</td></tr></table>
</td></tr>`;
  }

  let html = `
<tr><td bgcolor="${BRAND.surface}" class="tg-pad-mobile" style="background-color:${BRAND.surface};padding:24px 32px;font-size:0;line-height:0;text-align:center;">
<img src="${imageUrl}" alt="${imageAlt}" width="${declaredWidth}" class="tg-img-fluid" style="display:inline-block;width:100%;max-width:${declaredWidth}px;height:auto;border:0;outline:none;text-decoration:none;border-radius:8px;">
</td></tr>`;

  if (caption) {
    html += `
<tr><td bgcolor="${BRAND.surface}" class="tg-pad-mobile" style="background-color:${BRAND.surface};padding:0 32px 24px 32px;text-align:center;">
<div style="font-family:${FONTS.body};font-style:italic;font-size:14px;color:${BRAND.inkSoft};line-height:20px;margin:0;">${caption}</div>
</td></tr>`;
  }

  return html;
}

const schema = {
  type: "generated-image",
  label: "Generated image",
  description: "A single AI-generated visual. Use when the image is the message — product mockups, comparison cards, pricing visuals, data blocks.",
  fields: [
    { key: "imageUrl", label: "Image URL", type: "url", help: "Click Generate to create. URL comes from the Stage B image pipeline." },
    { key: "imageAlt", label: "Alt text", type: "text", required: true, maxLength: 200 },
    { key: "caption", label: "Caption (optional)", type: "text", maxLength: 200 },
    { key: "width",  label: "Native width",  type: "text", help: "Pipeline returns 2400px wide; rendered to 600px in email" },
    { key: "height", label: "Native height", type: "text" },
    // _briefSpec holds the inputs used to generate the image so the user
    // can regenerate or audit. Hidden from the field renderer with type:'hidden'.
    // The Generate modal writes this; the renderer never reads it.
    { key: "_briefSpec", label: "Brief inputs (internal)", type: "hidden" },
  ],
  // Composer hints — surfaced into the system prompt at Layer 5
  composerHints: {
    whenToUse: [
      "Product mockups (Apple-style screenshots of Travelgenix products in use)",
      "Comparison cards (us vs the alternative, before vs after)",
      "Pricing tables where the design itself is the message",
      "Hero stat blocks or value-prop cards where typography is the visual",
      "Destination spotlights that need editorial polish beyond HTML",
    ],
    whenNotToUse: [
      "Hero + body copy where text and image work together (use hero or hero-image)",
      "Photography of real places or people (route to Pexels lifestyle instead)",
      "Anything the user will need to edit after generation (text is baked into the PNG)",
    ],
  },
};

module.exports = { render, schema };
