// api/campaign-list.js
//
// Lists the drafts created by the Promote campaign generator (Product Brain →
// Promote), separate from normal cron/manual content. Reads the "Generated By"
// = "Promote" marker on Post Queue and Email Queue.
//
// GET /api/campaign-list?tenantId=recXXX
//   → { ok, posts: [...], emails: [...] }
//
// Auth: cookie session via id.travelify.io; owner may target any tenant, others
// only their own. Same pattern as product-brain.js.
//
// Author: Travelgenix
// Date:   16 June 2026

const AIRTABLE_KEY = process.env.AIRTABLE_KEY;
const AIRTABLE_BASE = "appSoIlSe0sNaJ4BZ";
const POST_QUEUE_TABLE = "tblbhyiuULvedva0K";
const EMAIL_QUEUE_TABLE = "tblzM5FsiLiriVLT1";
const PRODUCTS_TABLE = "tblGBl8X3RIVnCwDM";
const CLIENTS_TABLE = "tblUkzvBujc94Yali";
const ID_HOST = "https://id.travelify.io";
const OWNER_CLIENT_ID = "recFXQY7be6gMr4In";

async function validateSession(req) {
  const cookie = req.headers.cookie || "";
  if (!cookie.match(/(?:^|;\s*)tg_session=/)) return { ok: false, status: 401, error: "Not signed in" };
  try {
    const meRes = await fetch(`${ID_HOST}/api/auth/me`, { method: "GET", headers: { cookie } });
    if (meRes.status === 401) return { ok: false, status: 401, error: "Session expired" };
    if (!meRes.ok) return { ok: false, status: 502, error: "Auth check failed" };
    const data = await meRes.json();
    if (!data || !data.ok || !data.user || !data.user.email) return { ok: false, status: 401, error: "Invalid session" };
    return { ok: true, email: String(data.user.email).trim().toLowerCase() };
  } catch (err) { return { ok: false, status: 502, error: "Auth check failed" }; }
}

async function lookupTenantsForEmail(email) {
  const formula = encodeURIComponent(`LOWER({Monthly Report Email})='${email.replace(/'/g, "\\'")}'`);
  const url = `https://api.airtable.com/v0/${AIRTABLE_BASE}/${CLIENTS_TABLE}?filterByFormula=${formula}&maxRecords=10&fields[]=Business Name`;
  const r = await fetch(url, { headers: { Authorization: `Bearer ${AIRTABLE_KEY}` } });
  if (!r.ok) return [];
  const d = await r.json();
  return ((d && d.records) || []).map(rec => rec.id);
}

async function authorise(req, targetTenantId) {
  const session = await validateSession(req);
  if (!session.ok) return session;
  const tenantIds = await lookupTenantsForEmail(session.email);
  if (tenantIds.length === 0) return { ok: false, status: 404, error: "No tenant profile found for your account" };
  const isOwner = tenantIds.includes(OWNER_CLIENT_ID);
  if (isOwner) return { ok: true, isOwner: true, effectiveTenantId: targetTenantId || OWNER_CLIENT_ID };
  if (targetTenantId && !tenantIds.includes(targetTenantId)) return { ok: false, status: 403, error: "Not authorised for that tenant" };
  return { ok: true, isOwner: false, effectiveTenantId: targetTenantId || tenantIds[0] };
}

async function airtableList(tableId, formula) {
  const params = new URLSearchParams({ pageSize: "100", filterByFormula: formula });
  const url = `https://api.airtable.com/v0/${AIRTABLE_BASE}/${tableId}?${params.toString()}`;
  const r = await fetch(url, { headers: { Authorization: `Bearer ${AIRTABLE_KEY}` } });
  if (!r.ok) { const t = await r.text().catch(() => ""); throw new Error(`Airtable ${r.status}: ${t.slice(0, 200)}`); }
  const d = await r.json();
  return d.records || [];
}

async function productNameMap() {
  // Small catalogue; one fetch, build id → name.
  const params = new URLSearchParams({ pageSize: "100", "fields[]": "Name" });
  const url = `https://api.airtable.com/v0/${AIRTABLE_BASE}/${PRODUCTS_TABLE}?${params.toString()}`;
  const r = await fetch(url, { headers: { Authorization: `Bearer ${AIRTABLE_KEY}` } });
  const map = {};
  if (r.ok) { const d = await r.json(); (d.records || []).forEach(rec => { map[rec.id] = (rec.fields && rec.fields["Name"]) || rec.id; }); }
  return map;
}

function inTenant(rec, tenantId) {
  const c = (rec.fields && rec.fields["Client"]) || [];
  return c.includes(tenantId);
}

module.exports = async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", req.headers.origin || "*");
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  res.setHeader("Cache-Control", "no-store");
  if (req.method === "OPTIONS") return res.status(204).end();
  if (req.method !== "GET") return res.status(405).json({ error: "GET only" });
  if (!AIRTABLE_KEY) return res.status(500).json({ error: "Service not configured" });

  try {
    const auth = await authorise(req, req.query.tenantId || null);
    if (!auth.ok) return res.status(auth.status).json({ error: auth.error });
    const tenant = auth.effectiveTenantId;

    const promoFormula = `{Generated By}='Promote'`;
    const [postRecs, emailRecs, names] = await Promise.all([
      airtableList(POST_QUEUE_TABLE, promoFormula),
      airtableList(EMAIL_QUEUE_TABLE, promoFormula),
      productNameMap()
    ]);

    const posts = postRecs.filter(r => inTenant(r, tenant)).map(rec => {
      const f = rec.fields || {};
      const prod = (f["Promoted Product"] || [])[0];
      const img = f["Image URL - Landscape"] || f["Image URL"] || "";
      return {
        id: rec.id,
        title: f["Post Title"] || "(untitled)",
        status: (f["Status"] && f["Status"].name) || f["Status"] || "",
        product: prod ? (names[prod] || "") : "",
        week: f["Generated Week"] || "",
        hasImage: !!img,
        imageUrl: img,
        createdTime: rec.createdTime
      };
    }).sort((a, b) => new Date(b.createdTime) - new Date(a.createdTime));

    const emails = emailRecs.filter(r => inTenant(r, tenant)).map(rec => {
      const f = rec.fields || {};
      return {
        id: rec.id,
        subject: f["Subject"] || "(no subject)",
        status: (f["Status"] && f["Status"].name) || f["Status"] || "",
        audience: (f["Audience"] && f["Audience"].name) || f["Audience"] || "",
        emailType: (f["Email Type"] && f["Email Type"].name) || f["Email Type"] || "",
        createdTime: rec.createdTime
      };
    }).sort((a, b) => new Date(b.createdTime) - new Date(a.createdTime));

    return res.status(200).json({ ok: true, tenantId: tenant, posts, emails });
  } catch (err) {
    console.error("[campaign-list] error:", err);
    return res.status(500).json({ error: err.message || "Internal error" });
  }
};
